// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Direct (non-pooled) connection: prisma migrate needs a session-level
    // advisory lock, which hangs indefinitely through the PgBouncer pooler
    // used by DATABASE_URL.
    url: process.env["DIRECT_URL"],
  },
});
